# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Qt\projects\vsqt_demo\src\demo_buttn.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_demo_buttn(object):
    def setupUi(self, demo_buttn):
        demo_buttn.setObjectName("demo_buttn")
        demo_buttn.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(demo_buttn)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        demo_buttn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(demo_buttn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        demo_buttn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(demo_buttn)
        self.statusbar.setObjectName("statusbar")
        demo_buttn.setStatusBar(self.statusbar)

        self.retranslateUi(demo_buttn)
        QtCore.QMetaObject.connectSlotsByName(demo_buttn)

    def retranslateUi(self, demo_buttn):
        _translate = QtCore.QCoreApplication.translate
        demo_buttn.setWindowTitle(_translate("demo_buttn", "MainWindow"))
        self.pushButton.setText(_translate("demo_buttn", "按钮"))
        self.pushButton_2.setText(_translate("demo_buttn", "PushButton"))
