# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Qt\projects\vsqt_demo\src\form_demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_demo(object):
    def setupUi(self, Form_demo):
        Form_demo.setObjectName("Form_demo")
        Form_demo.resize(584, 483)
        self.label = QtWidgets.QLabel(Form_demo)
        self.label.setGeometry(QtCore.QRect(100, 90, 54, 12))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form_demo)
        self.pushButton.setGeometry(QtCore.QRect(250, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form_demo)
        QtCore.QMetaObject.connectSlotsByName(Form_demo)

    def retranslateUi(self, Form_demo):
        _translate = QtCore.QCoreApplication.translate
        Form_demo.setWindowTitle(_translate("Form_demo", "Form"))
        self.label.setText(_translate("Form_demo", "文字"))
        self.pushButton.setText(_translate("Form_demo", "按钮"))
